### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by jperl** [atbaker/hypermasher#2]
Does the site require a password now? I wanted to share it with a friend.

**Comment by atbaker** [comment]
Hey @jperl - thanks for letting me know. I actually let the `hypermasher.com` domain name expire last year because I no longer maintain this project. I also believe Instagram sunsetted the main API this project uses.

I just added a note to the README which makes clear that I no longer work on this project and no longer own the domain.

If you're just curious about the project, I uploaded a screen recording of the site to YouTube a couple years ago: https://www.youtube.com/watch?v=oEN_ilJOexg

Thanks again for bringing this to my attention.
